"""Earth briefs you: proactive AOI briefing built on groundstation tools.

Instead of you asking Earth the right question, Earth tells you what you need
to know. Gathers events (EONET/GDACS), weather (Open-Meteo), and fresh
imagery (STAC) for a place, has Claude synthesize a decision-ready brief, and
writes a shareable HTML page with an interactive map. Cron it for real dailies.

    uv run briefing/brief.py --place "Chelan County, Washington" --days 7
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from groundstation import tools  # noqa: E402

SYNTH_PROMPT = """You are writing a daily Earth briefing for a decision maker who cares about this
area of interest. You are given raw monitoring data as JSON. Write a concise brief in markdown with
exactly these sections:

## TL;DR
2-3 sentences: overall situation, the one thing that needs attention, alert level (CALM / WATCH / ACT).

## What changed
Bullets on events (fires, floods, storms) in or near the AOI — name, how close, trend if inferable.
If none, say so in one line.

## Weather signal
2-3 bullets: notable recent weather and the week ahead — heat, wind, precipitation, anything that
compounds the events above. Include numbers with units.

## Fresh eyes on the ground
Which new satellite scenes arrived, their dates and cloud cover, and what to look at first.

## Suggested next steps
2-4 concrete actions (e.g. "task a closer look at X", "compare NDVI vs last month", "no action needed").

Rules: be specific, cite dates, no filler, no speculation beyond the data. If data sections have
errors or are empty, work with what's there and note the gap in one clause, not a paragraph.

DATA:
"""

PAGE = """<!doctype html>
<html><head><meta charset="utf-8"><title>Earth brief: __PLACE__</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { margin: 0; font: 16px/1.55 system-ui, sans-serif; color: #1c2430; background: #f4f5f2; }
  header { background: #10222e; color: #fff; padding: 28px 24px; }
  header h1 { margin: 0 0 4px; font-size: 24px; }
  header p { margin: 0; opacity: .75; font-size: 14px; }
  main { max-width: 860px; margin: 0 auto; padding: 24px; }
  .card { background: #fff; border-radius: 12px; padding: 20px 24px; margin: 16px 0;
          box-shadow: 0 1px 4px rgba(0,0,0,.08); }
  .card img { max-width: 100%; border-radius: 8px; }
  h2 { font-size: 17px; margin: 18px 0 6px; }
  a.button { display: inline-block; background: #10222e; color: #fff; text-decoration: none;
             padding: 10px 16px; border-radius: 8px; font-size: 14px; margin-top: 8px; }
  footer { text-align: center; color: #777; font-size: 12px; padding: 16px; }
  ul { margin: 4px 0; padding-left: 22px; }
</style></head><body>
<header><h1>&#127758; Earth brief: __PLACE__</h1><p>__DATE__ &middot; generated by groundstation, unprompted</p></header>
<main>
<div class="card">__BODY__</div>
<div class="card"><h2>Latest scene</h2><p>__SCENE_CAPTION__</p><img src="__PREVIEW__" alt="latest satellite preview">
<br><a class="button" href="__MAP__">Open interactive map</a></div>
</main>
<footer>groundstation &middot; Development Seed labs prototype &middot; STAC + TiTiler + EONET + GDACS + Open-Meteo</footer>
</body></html>
"""


def md_to_html(md: str) -> str:
    out, in_list = [], False
    for line in md.splitlines():
        s = line.strip()
        if s.startswith("## "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<h2>{s[3:]}</h2>")
        elif s.startswith(("- ", "* ")):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{s[2:]}</li>")
        elif s:
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<p>{s}</p>")
    if in_list:
        out.append("</ul>")
    html = "\n".join(out)
    html = html.replace("**", "")  # keep it simple; bold markers read fine stripped
    return html


def synthesize(data: dict) -> str:
    prompt = SYNTH_PROMPT + json.dumps(data, default=str)
    try:
        r = subprocess.run(
            ["claude", "-p", "--model", "sonnet"],
            input=prompt,
            capture_output=True,
            text=True,
            timeout=240,
        )
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip()
        print(f"claude -p failed ({r.returncode}): {r.stderr[:200]}", file=sys.stderr)
    except FileNotFoundError:
        print("claude CLI not found; writing data-only brief", file=sys.stderr)
    except subprocess.TimeoutExpired:
        print("claude -p timed out; writing data-only brief", file=sys.stderr)
    # Deterministic fallback so the pipeline never produces nothing
    ev = data["events"]
    lines = ["## TL;DR", f"Automated data summary for {data['place']} (no LLM synthesis available)."]
    lines += ["## What changed"] + [
        f"- {e['category']}: {e['title']} ({e.get('date','')})" for e in ev.get("eonet", [])[:8]
    ] or ["- No open events."]
    lines += ["## Fresh eyes on the ground"] + [
        f"- {i['collection']} {i['datetime'][:10]} cloud {i.get('cloud_cover')}%"
        for i in data["imagery"].get("items", [])[:5]
    ]
    return "\n".join(lines)


def build_brief(place: str, days: int, out_dir: Path) -> Path:
    today = dt.date.today()
    print(f"[1/5] geocoding {place!r}...")
    g = tools.geocode(place)
    if "error" in g:
        raise SystemExit(g["error"])
    bbox = g["bbox"]
    pad = 0.4  # look slightly beyond the AOI for nearby events
    ev_bbox = [bbox[0] - pad, bbox[1] - pad, bbox[2] + pad, bbox[3] + pad]

    print("[2/5] gathering events + weather...")
    events = tools.active_events(bbox=ev_bbox, days=30)
    weather = tools.weather_summary(g["lat"], g["lon"], past_days=7)

    print("[3/5] searching fresh imagery...")
    since = (today - dt.timedelta(days=days)).isoformat()
    imagery = tools.search_imagery(
        "earth-search",
        ["sentinel-2-l2a"],
        bbox=bbox,
        datetime_range=f"{since}T00:00:00Z/{today.isoformat()}T23:59:59Z",
        max_cloud_cover=40,
        limit=8,
    )

    best = min(
        imagery.get("items", []),
        key=lambda i: (i.get("cloud_cover") or 100),
        default=None,
    )

    print("[4/5] rendering map + preview...")
    fc = {"type": "FeatureCollection", "features": []}
    for e in events.get("eonet", []):
        if e.get("coordinates"):
            fc["features"].append(
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": e["coordinates"]},
                    "properties": {"title": e["title"], "description": f"{e['category']} · {e.get('date', '')[:10]}"},
                }
            )
    for e in events.get("gdacs", []):
        if e.get("coordinates") and e["coordinates"][0] is not None:
            fc["features"].append(
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": e["coordinates"]},
                    "properties": {"title": e["title"], "description": f"GDACS {e['type']} · alert {e['alert_level']}"},
                }
            )
    layers = []
    preview_url = ""
    scene_caption = "No sufficiently cloud-free scene in the window."
    if best:
        layers.append(
            {
                "type": "item",
                "name": f"Sentinel-2 {best['datetime'][:10]} ({round(best.get('cloud_cover') or 0, 1)}% cloud)",
                "catalog": "earth-search",
                "collection_id": best["collection"],
                "item_id": best["id"],
                "assets": ["visual"],
            }
        )
        preview_url = tools.preview_item("earth-search", best["collection"], best["id"], max_size=768)["preview_url"]
        scene_caption = (
            f"Sentinel-2, {best['datetime'][:10]}, {round(best.get('cloud_cover') or 0, 1)}% cloud cover — "
            f"clearest of {imagery['count']} scenes in the last {days} days."
        )
    if fc["features"]:
        layers.append({"type": "geojson", "name": f"Active events ({len(fc['features'])})", "data": fc, "color": "#d63b3b"})

    out_dir.mkdir(parents=True, exist_ok=True)
    slug = "".join(ch if ch.isalnum() else "-" for ch in place.lower())[:40].strip("-")
    map_path = out_dir / f"brief-map-{slug}-{today.isoformat()}.html"
    tools.render_map(
        title=f"Earth brief: {place}",
        subtitle=f"{today.isoformat()} · latest imagery + active events",
        bbox=ev_bbox,
        layers=layers or [{"type": "geojson", "name": "AOI", "data": fc, "color": "#d63b3b"}],
        out_path=str(map_path),
    )

    print("[5/5] synthesizing brief with Claude...")
    data = {
        "place": place,
        "resolved_name": g["name"],
        "date": today.isoformat(),
        "aoi_bbox": bbox,
        "events": events,
        "weather": weather,
        "imagery": {"count": imagery.get("count"), "items": imagery.get("items", [])[:8]},
    }
    md = synthesize(data)

    html = (
        PAGE.replace("__PLACE__", place)
        .replace("__DATE__", today.strftime("%A, %B %d, %Y"))
        .replace("__BODY__", md_to_html(md))
        .replace("__PREVIEW__", preview_url)
        .replace("__SCENE_CAPTION__", scene_caption)
        .replace("__MAP__", map_path.name)
    )
    brief_path = out_dir / f"brief-{slug}-{today.isoformat()}.html"
    brief_path.write_text(html)
    (out_dir / f"brief-{slug}-{today.isoformat()}.md").write_text(md)
    print(f"brief: {brief_path}\nmap:   {map_path}")
    return brief_path


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--place", required=True)
    ap.add_argument("--days", type=int, default=7, help="imagery lookback window")
    ap.add_argument("--out", default="demo", help="output directory")
    args = ap.parse_args()
    build_brief(args.place, args.days, Path(args.out))
