"""Earth briefs you: proactive AOI briefing built on groundstation tools.

Instead of you asking Earth the right question, Earth tells you what you need
to know. Gathers events (EONET/GDACS), weather (Open-Meteo), and fresh
imagery (STAC) for a place, has Claude synthesize a decision-ready brief, and
writes a shareable HTML page with an interactive map. Cron it for real dailies.

    uv run briefing/brief.py --place "Chelan County, Washington" --days 7
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from groundstation import tools  # noqa: E402

SYNTH_PROMPT = """You are writing a daily Earth briefing for a decision maker who cares about this
area of interest. You are given raw monitoring data as JSON. Write a concise brief in markdown with
exactly these sections:

## TL;DR
2-3 sentences: overall situation, the one thing that needs attention, alert level (CALM / WATCH / ACT).

## What changed
Bullets on events (fires, floods, storms) in or near the AOI — name, how close, trend if inferable.
If none, say so in one line.

## Weather signal
2-3 bullets: notable recent weather and the week ahead — heat, wind, precipitation, anything that
compounds the events above. Include numbers with units.

## Fresh eyes on the ground
Which new satellite scenes arrived, their dates and cloud cover, and what to look at first.

## Suggested next steps
2-4 concrete actions (e.g. "task a closer look at X", "compare NDVI vs last month", "no action needed").

Rules: be specific, cite dates, no filler, no speculation beyond the data. If data sections have
errors or are empty, work with what's there and note the gap in one clause, not a paragraph.
If an "ndvi_change" block is present, weave the vegetation delta (with both dates) into TL;DR and
What changed — a real change signal outranks scene bookkeeping.
If a "previous_run" block is present, "What changed" means changed SINCE THAT RUN: name events that
appeared, escalated, or cleared since it, and say plainly when today is calmer than the last run
(e.g. "yesterday's WATCH stands down"). Deltas against the last run outrank everything else.

DATA:
"""

PAGE = """<!doctype html>
<html><head><meta charset="utf-8"><title>Earth brief: __PLACE__</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { margin: 0; font: 16px/1.55 system-ui, sans-serif; color: #1c2430; background: #f4f5f2; }
  header { background: #10222e; color: #fff; padding: 28px 24px; }
  header h1 { margin: 0 0 4px; font-size: 24px; }
  header p { margin: 0; opacity: .75; font-size: 14px; }
  main { max-width: 860px; margin: 0 auto; padding: 24px; }
  .card { background: #fff; border-radius: 12px; padding: 20px 24px; margin: 16px 0;
          box-shadow: 0 1px 4px rgba(0,0,0,.08); }
  .card img { max-width: 100%; border-radius: 8px; }
  h2 { font-size: 17px; margin: 18px 0 6px; }
  a.button { display: inline-block; background: #10222e; color: #fff; text-decoration: none;
             padding: 10px 16px; border-radius: 8px; font-size: 14px; margin-top: 8px; }
  footer { text-align: center; color: #777; font-size: 12px; padding: 16px; }
  ul { margin: 4px 0; padding-left: 22px; }
</style></head><body>
<header><h1>&#127758; Earth brief: __PLACE__</h1><p>__DATE__ &middot; generated by groundstation, unprompted</p></header>
<main>
<div class="card">__BODY__</div>
<div class="card"><h2>Latest scene</h2><p>__SCENE_CAPTION__</p><img src="__PREVIEW__" alt="latest satellite preview">
<br><a class="button" href="__MAP__">Open interactive map</a></div>
</main>
<footer>groundstation &middot; Development Seed labs prototype &middot; STAC + TiTiler + EONET + GDACS + Open-Meteo</footer>
</body></html>
"""


def md_to_html(md: str) -> str:
    out, in_list = [], False
    for line in md.splitlines():
        s = line.strip()
        if s.startswith("## "):
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<h2>{s[3:]}</h2>")
        elif s.startswith(("- ", "* ")):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{s[2:]}</li>")
        elif s:
            if in_list:
                out.append("</ul>")
                in_list = False
            out.append(f"<p>{s}</p>")
    if in_list:
        out.append("</ul>")
    html = "\n".join(out)
    html = html.replace("**", "")  # keep it simple; bold markers read fine stripped
    return html


def synthesize(data: dict) -> str:
    prompt = SYNTH_PROMPT + json.dumps(data, default=str)
    try:
        r = subprocess.run(
            ["claude", "-p", "--model", "sonnet"],
            input=prompt,
            capture_output=True,
            text=True,
            timeout=240,
            shell=(sys.platform == "win32"),
        )
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip()
        print(f"claude -p failed ({r.returncode}): {r.stderr[:200]}", file=sys.stderr)
    except FileNotFoundError:
        print("claude CLI not found; writing data-only brief", file=sys.stderr)
    except subprocess.TimeoutExpired:
        print("claude -p timed out; writing data-only brief", file=sys.stderr)
    # Deterministic fallback so the pipeline never produces nothing
    ev = data["events"]
    lines = ["## TL;DR", f"Automated data summary for {data['place']} (no LLM synthesis available)."]
    lines += ["## What changed"] + [
        f"- {e['category']}: {e['title']} ({e.get('date','')})" for e in ev.get("eonet", [])[:8]
    ] or ["- No open events."]
    lines += ["## Fresh eyes on the ground"] + [
        f"- {i['collection']} {i['datetime'][:10]} cloud {i.get('cloud_cover')}%"
        for i in data["imagery"].get("items", [])[:5]
    ]
    return "\n".join(lines)


def ndvi_change(best: dict, today: dt.date, days: int) -> dict | None:
    """NDVI delta between the newest scene and a same-tile baseline ~1 month back."""
    tile = best["id"].split("_")[1] if "_" in best["id"] else None
    if not tile:
        return None
    end = today - dt.timedelta(days=days + 1)
    start = today - dt.timedelta(days=days + 45)
    baseline = tools.search_imagery(
        "earth-search",
        [best["collection"]],
        bbox=best["bbox"],
        datetime_range=f"{start.isoformat()}T00:00:00Z/{end.isoformat()}T23:59:59Z",
        max_cloud_cover=30,
        limit=20,
    )
    candidates = [i for i in baseline.get("items", []) if f"_{tile}_" in i["id"]]
    if not candidates:
        return None
    ref = min(candidates, key=lambda i: i.get("cloud_cover") or 100)
    expr = "(nir-red)/(nir+red)"
    now_s = tools.compute_statistics("earth-search", best["collection"], best["id"], expression=expr)
    ref_s = tools.compute_statistics("earth-search", ref["collection"], ref["id"], expression=expr)
    now_mean = next(iter(now_s.values()))["mean"]
    ref_mean = next(iter(ref_s.values()))["mean"]
    return {
        "metric": "NDVI (vegetation) over MGRS tile " + tile,
        "current": {"scene": best["id"], "date": best["datetime"][:10], "mean": round(now_mean, 3)},
        "baseline": {"scene": ref["id"], "date": ref["datetime"][:10], "mean": round(ref_mean, 3)},
        "delta": round(now_mean - ref_mean, 3),
        "delta_pct": round((now_mean - ref_mean) / abs(ref_mean) * 100, 1) if ref_mean else None,
    }


def build_brief(place: str, days: int, out_dir: Path) -> dict:
    today = dt.date.today()
    print(f"[1/5] geocoding {place!r}...")
    g = tools.geocode(place)
    if "error" in g:
        raise SystemExit(g["error"])
    bbox = g["bbox"]
    pad = 0.4  # look slightly beyond the AOI for nearby events
    ev_bbox = [bbox[0] - pad, bbox[1] - pad, bbox[2] + pad, bbox[3] + pad]

    print("[2/5] gathering events + weather...")
    events = tools.active_events(bbox=ev_bbox, days=30)
    weather = tools.weather_summary(g["lat"], g["lon"], past_days=7)

    print("[3/5] searching fresh imagery...")
    since = (today - dt.timedelta(days=days)).isoformat()
    imagery = tools.search_imagery(
        "earth-search",
        ["sentinel-2-l2a"],
        bbox=bbox,
        datetime_range=f"{since}T00:00:00Z/{today.isoformat()}T23:59:59Z",
        max_cloud_cover=40,
        limit=8,
    )

    best = min(
        imagery.get("items", []),
        key=lambda i: (i.get("cloud_cover") or 100),
        default=None,
    )

    change = None
    if best:
        print("[3.5/5] computing NDVI change vs baseline...")
        try:
            change = ndvi_change(best, today, days)
        except Exception as e:
            print(f"change detection skipped: {e}", file=sys.stderr)

    print("[4/5] rendering map + preview...")
    fc = {"type": "FeatureCollection", "features": []}
    for e in events.get("eonet", []):
        if e.get("coordinates"):
            fc["features"].append(
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": e["coordinates"]},
                    "properties": {"title": e["title"], "description": f"{e['category']} · {e.get('date', '')[:10]}"},
                }
            )
    for e in events.get("gdacs", []):
        if e.get("coordinates") and e["coordinates"][0] is not None:
            fc["features"].append(
                {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": e["coordinates"]},
                    "properties": {"title": e["title"], "description": f"GDACS {e['type']} · alert {e['alert_level']}"},
                }
            )
    layers = []
    preview_url = ""
    scene_caption = "No sufficiently cloud-free scene in the window."
    if best:
        layers.append(
            {
                "type": "item",
                "name": f"Sentinel-2 {best['datetime'][:10]} ({round(best.get('cloud_cover') or 0, 1)}% cloud)",
                "catalog": "earth-search",
                "collection_id": best["collection"],
                "item_id": best["id"],
                "assets": ["visual"],
            }
        )
        preview_url = tools.preview_item("earth-search", best["collection"], best["id"], max_size=768)["preview_url"]
        scene_caption = (
            f"Sentinel-2, {best['datetime'][:10]}, {round(best.get('cloud_cover') or 0, 1)}% cloud cover — "
            f"clearest of {imagery['count']} scenes in the last {days} days."
        )
    if fc["features"]:
        layers.append({"type": "geojson", "name": f"Active events ({len(fc['features'])})", "data": fc, "color": "#d63b3b"})

    out_dir.mkdir(parents=True, exist_ok=True)
    slug = "".join(ch if ch.isalnum() else "-" for ch in place.lower())[:40].strip("-")
    map_path = out_dir / f"brief-map-{slug}-{today.isoformat()}.html"
    tools.render_map(
        title=f"Earth brief: {place}",
        subtitle=f"{today.isoformat()} · latest imagery + active events",
        bbox=ev_bbox,
        layers=layers or [{"type": "geojson", "name": "AOI", "data": fc, "color": "#d63b3b"}],
        out_path=str(map_path),
    )

    print("[5/5] synthesizing brief with Claude...")
    data = {
        "place": place,
        "resolved_name": g["name"],
        "date": today.isoformat(),
        "aoi_bbox": bbox,
        "events": events,
        "weather": weather,
        "imagery": {"count": imagery.get("count"), "items": imagery.get("items", [])[:8]},
    }
    if change:
        data["ndvi_change"] = change
    state_path = Path(__file__).parent / "state" / f"{slug}.json"
    if state_path.exists():
        try:
            data["previous_run"] = json.loads(state_path.read_text(encoding="utf-8"))
        except Exception:
            pass
    md = synthesize(data)

    html = (
        PAGE.replace("__PLACE__", place)
        .replace("__DATE__", today.strftime("%A, %B %d, %Y"))
        .replace("__BODY__", md_to_html(md))
        .replace("__PREVIEW__", preview_url)
        .replace("__SCENE_CAPTION__", scene_caption)
        .replace("__MAP__", map_path.name)
    )
    brief_path = out_dir / f"brief-{slug}-{today.isoformat()}.html"
    brief_path.write_text(html, encoding="utf-8")
    (out_dir / f"brief-{slug}-{today.isoformat()}.md").write_text(md, encoding="utf-8")
    print(f"brief: {brief_path}\nmap:   {map_path}")
    alert_m = re.search(r"\b(CALM|WATCH|ACT)\b", md)
    tldr_m = re.search(r"## TL;DR\s*\n(.+?)(?=\n## |\Z)", md, re.S)
    result = {
        "place": place,
        "alert": alert_m.group(1) if alert_m else "CALM",
        "tldr": (tldr_m.group(1).strip() if tldr_m else "")[:400],
        "brief": brief_path.name,
        "map": map_path.name,
    }
    # memory for the next run: tomorrow's "what changed" diffs against this
    state_path.parent.mkdir(parents=True, exist_ok=True)
    state_path.write_text(json.dumps({
        "date": today.isoformat(),
        "alert": result["alert"],
        "event_titles": [e.get("title") for e in events.get("eonet", []) + events.get("gdacs", [])][:20],
        "ndvi_mean": change["current"]["mean"] if change else None,
        "scene_count": imagery.get("count"),
        "tldr": result["tldr"][:200],
    }, indent=1), encoding="utf-8")
    # also save the gathered data snapshot for the briefing evals
    (out_dir / f"brief-{slug}-{today.isoformat()}.data.json").write_text(
        json.dumps(data, default=str, indent=1), encoding="utf-8")
    return result


ALERT_COLORS = {"ACT": "#c0392b", "WATCH": "#e67e22", "CALM": "#2e7d32"}

INDEX = """<!doctype html>
<html><head><meta charset="utf-8"><title>Earth briefs: __DATE__</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { margin: 0; font: 16px/1.55 system-ui, sans-serif; color: #1c2430; background: #f4f5f2; }
  header { background: #10222e; color: #fff; padding: 28px 24px; }
  header h1 { margin: 0 0 4px; font-size: 24px; }
  header p { margin: 0; opacity: .75; font-size: 14px; }
  main { max-width: 860px; margin: 0 auto; padding: 24px; }
  .card { background: #fff; border-radius: 12px; padding: 18px 22px; margin: 14px 0;
          box-shadow: 0 1px 4px rgba(0,0,0,.08); }
  .badge { display: inline-block; color: #fff; font-size: 12px; font-weight: 600;
           padding: 3px 10px; border-radius: 999px; margin-left: 8px; vertical-align: 2px; }
  .card h2 { margin: 0 0 6px; font-size: 18px; }
  .card p { margin: 6px 0 10px; color: #333; }
  a.button { display: inline-block; background: #10222e; color: #fff; text-decoration: none;
             padding: 8px 14px; border-radius: 8px; font-size: 13px; margin-right: 8px; }
  footer { text-align: center; color: #777; font-size: 12px; padding: 16px; }
</style></head><body>
<header><h1>&#127758; Morning sweep</h1><p>__DATE__ &middot; __N__ areas of interest &middot; generated unprompted by groundstation</p></header>
<main>__CARDS__</main>
<footer>groundstation &middot; Development Seed labs prototype</footer>
</body></html>
"""


ALERT_EMOJI = {"ACT": "🔴", "WATCH": "🟠", "CALM": "🟢"}


def slack_payload(results: list[dict], today: dt.date) -> dict:
    lines = [f"🌍 *Morning sweep — {today.strftime('%A, %B %d')}* ({len(results)} areas)"]
    for r in results:
        first_sentence = (r["tldr"].split(". ")[0].rstrip(".") + ".").replace("**", "*")
        lines.append(f"{ALERT_EMOJI.get(r['alert'], '⚪')} *{r['alert']}* — {r['place']}: {first_sentence}")
    lines.append(f"_full briefs + maps: morning-sweep-{today.isoformat()}.html_")
    return {"text": "\n".join(lines)}


def deliver_slack(payload: dict, webhook: str | None, dry_run: bool) -> None:
    if dry_run:
        print("\n--- slack payload (dry run) ---")
        print(json.dumps(payload, indent=1, ensure_ascii=False))
        return
    if not webhook:
        return
    import httpx

    r = httpx.post(webhook, json=payload, timeout=30)
    print(f"slack delivery: {r.status_code}")


def build_fleet(config_path: Path, out_dir: Path, slack_webhook: str | None = None, slack_dry_run: bool = False) -> Path:
    aois = json.loads(config_path.read_text(encoding="utf-8"))
    results = []
    for aoi in aois:
        print(f"\n=== {aoi['place']} ===")
        try:
            results.append(build_brief(aoi["place"], aoi.get("days", 7), out_dir))
        except SystemExit as e:
            print(f"skipped {aoi['place']}: {e}", file=sys.stderr)
    order = {"ACT": 0, "WATCH": 1, "CALM": 2}
    results.sort(key=lambda r: order.get(r["alert"], 3))
    cards = "".join(
        f'<div class="card"><h2>{r["place"]}'
        f'<span class="badge" style="background:{ALERT_COLORS.get(r["alert"], "#777")}">{r["alert"]}</span></h2>'
        f'<p>{r["tldr"].replace("**", "")}</p>'
        f'<a class="button" href="{r["brief"]}">Full brief</a>'
        f'<a class="button" href="{r["map"]}">Map</a></div>'
        for r in results
    )
    today = dt.date.today()
    html = (
        INDEX.replace("__DATE__", today.strftime("%A, %B %d, %Y"))
        .replace("__N__", str(len(results)))
        .replace("__CARDS__", cards)
    )
    index_path = out_dir / f"morning-sweep-{today.isoformat()}.html"
    index_path.write_text(html, encoding="utf-8")
    print(f"\nindex: {index_path}")
    deliver_slack(slack_payload(results, today), slack_webhook, slack_dry_run)
    return index_path


if __name__ == "__main__":
    import os

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--place", help="single AOI")
    ap.add_argument("--fleet", help="path to JSON list of AOIs: [{place, days?}, ...]")
    ap.add_argument("--days", type=int, default=7, help="imagery lookback window")
    ap.add_argument("--out", default="demo", help="output directory")
    ap.add_argument("--slack-webhook", default=os.environ.get("SLACK_WEBHOOK_URL"),
                    help="post the sweep summary to this Slack incoming webhook (fleet mode)")
    ap.add_argument("--slack-dry-run", action="store_true", help="print the Slack payload instead of posting")
    args = ap.parse_args()
    if not args.place and not args.fleet:
        ap.error("provide --place or --fleet")
    if args.fleet:
        build_fleet(Path(args.fleet), Path(args.out), args.slack_webhook, args.slack_dry_run)
    else:
        build_brief(args.place, args.days, Path(args.out))
